# Site settings
site: Amitabh Borah
title: Amitabh Borah - Freelance Frontend Developer, Blogger & Part-time Motorcyclist
keywords: amitabh borah, amitabh borah resume
description: >-
  About Amitabh Borah, a Freelance Frontend Developer, Blog Writer and Owner, and a Part-time Motorcyclist and Traveler.
lang: en-US
timezone:  Asia/Kolakata
repo: # site repo [optional]
google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
discus-identifier:  XXX

# Author settings
author:
  name: Amitabh Borah
  bio: Freelance Frontend Developer <br> Founder offroadpioneers.com <br> Motorcyclist
  picture: assets/images/profile.jpg 
  github: its-aomi # github username
  twitter: # twitter username
  facebook: # facebook username
  instagram: # instagram username
  youtube: # youtube username
  linkedin: # linkedin username
  email: aomi@duck.com # email adress


# URL settings
url: "its-aomi.github.io/aomi-blog/" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
